/**
 * Typst Typesetting Engine — Huntflow Agent Hardening
 *
 * Fast (<30ms), zero-dependency, publication-grade resume typesetting
 * generating clean Typst markup (.typ) with ATS-optimized layouts.
 */

import { ResumeContent, ResumeDocKind } from "@/types";

/** Escape special Typst characters */
export function escapeTypst(text: string | undefined): string {
  if (!text) return "";
  return text
    .replace(/\\/g, "\\\\")
    .replace(/#/g, "\\#")
    .replace(/\$/g, "\\$")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]")
    .replace(/\*/g, "\\*")
    .replace(/_/g, "\\_")
    .replace(/@/g, "\\@")
    .replace(/</g, "\\<")
    .replace(/>/g, "\\>");
}

export interface TypstRenderOptions {
  templateId?: string;
  docKind?: ResumeDocKind;
  accentColor?: string;
  fontFamily?: "sans" | "serif" | "mono";
}

/**
 * Render structured resume content into valid Typst markup (.typ).
 */
export function renderTypstResume(
  templateId: string = "classic-ats",
  content: ResumeContent,
  opts: TypstRenderOptions = {}
): string {
  const h = content.header || {
    name: "Candidate",
    title: "",
    email: "",
    phone: "",
    location: "",
    linkedin: "",
    github: "",
    portfolio: "",
  };
  const name = escapeTypst(h.name || "Candidate");
  const title = escapeTypst(h.title || "");
  const email = escapeTypst(h.email || "");
  const phone = escapeTypst(h.phone || "");
  const location = escapeTypst(h.location || "");
  const linkedin = escapeTypst(h.linkedin || "");
  const github = escapeTypst(h.github || "");
  const portfolio = escapeTypst(h.portfolio || "");

  const contacts = [email, phone, location, linkedin, github, portfolio].filter(Boolean).join("  •  ");

  const font =
    opts.fontFamily === "mono"
      ? '"JetBrains Mono", monospace'
      : opts.fontFamily === "serif"
        ? '"STIX Two Text", serif'
        : '"Manrope", sans-serif';
  const isGerman = templateId === "tabular-german";
  const isFrench = templateId === "modern-french";

  const lines: string[] = [
    `// Generated by HUNTFLOW Typst Engine`,
    `#set page(paper: "a4", margin: (x: 1.8cm, y: 1.8cm))`,
    `#set text(font: ${font}, size: 10pt, fill: rgb("#111827"))`,
    `#set par(justify: false, leading: 0.65em)`,
    ``,
    `// Header`,
    `#align(center)[`,
    `  #text(size: 18pt, weight: "bold")[${name}] \\`,
  ];

  if (title) {
    lines.push(`  #v(-2pt)#text(size: 11pt, weight: "medium", fill: rgb("#4b5563"))[${title}] \\`);
  }

  if (contacts) {
    lines.push(`  #v(2pt)#text(size: 8.5pt, fill: rgb("#6b7280"))[${contacts}]`);
  }

  lines.push(`]`, `#v(8pt)`);

  // Summary Section
  if (content.summary && content.summary.trim()) {
    const summaryTitle = isGerman ? "Profil" : isFrench ? "Profil Professionnel" : "Professional Summary";
    lines.push(
      `#block(width: 100%)[`,
      `  #text(size: 11pt, weight: "bold", fill: rgb("#1f2937"))[${summaryTitle}]`,
      `  #line(length: 100%, stroke: 0.5pt + rgb("#e5e7eb"))`,
      `  #v(2pt)`,
      `  #text(size: 9.5pt)[${escapeTypst(content.summary)}]`,
      `]`,
      `#v(8pt)`
    );
  }

  // Skills Section
  if (content.skills && content.skills.length > 0) {
    const skillsTitle = isGerman ? "Kenntnisse & Fähigkeiten" : isFrench ? "Compétences Clés" : "Technical Skills";
    const skillList = content.skills.map((s) => escapeTypst(s)).join("  •  ");
    lines.push(
      `#block(width: 100%)[`,
      `  #text(size: 11pt, weight: "bold", fill: rgb("#1f2937"))[${skillsTitle}]`,
      `  #line(length: 100%, stroke: 0.5pt + rgb("#e5e7eb"))`,
      `  #v(2pt)`,
      `  #text(size: 9.5pt)[${skillList}]`,
      `]`,
      `#v(8pt)`
    );
  }

  // Experience Section
  if (content.experience && content.experience.length > 0) {
    const expTitle = isGerman ? "Berufserfahrung" : isFrench ? "Expérience Professionnelle" : "Work Experience";
    lines.push(
      `#block(width: 100%)[`,
      `  #text(size: 11pt, weight: "bold", fill: rgb("#1f2937"))[${expTitle}]`,
      `  #line(length: 100%, stroke: 0.5pt + rgb("#e5e7eb"))`,
      `  #v(4pt)`
    );

    for (const item of content.experience) {
      const role = escapeTypst(item.role || "");
      const company = escapeTypst(item.company || "");
      const duration = escapeTypst(item.duration || "");

      lines.push(
        `  #grid(columns: (1fr, auto),`,
        `    [#text(weight: "bold", size: 10pt)[${role}] #if "${company}" != "" [--- #text(style: "italic")[${company}]]],`,
        `    [#text(size: 8.5pt, fill: rgb("#6b7280"))[${duration}]]`,
        `  )`
      );

      if (item.bullets && item.bullets.length > 0) {
        lines.push(`  #v(1pt)`);
        for (const b of item.bullets) {
          lines.push(`  - #text(size: 9pt)[${escapeTypst(b)}]`);
        }
      }
      lines.push(`  #v(6pt)`);
    }

    lines.push(`]`, `#v(4pt)`);
  }

  // Education Section
  if (content.education && content.education.length > 0) {
    const eduTitle = isGerman ? "Ausbildung" : isFrench ? "Formation" : "Education";
    lines.push(
      `#block(width: 100%)[`,
      `  #text(size: 11pt, weight: "bold", fill: rgb("#1f2937"))[${eduTitle}]`,
      `  #line(length: 100%, stroke: 0.5pt + rgb("#e5e7eb"))`,
      `  #v(4pt)`
    );

    for (const item of content.education) {
      const degree = escapeTypst(item.degree || "");
      const school = escapeTypst(item.school || "");
      const year = escapeTypst(item.year || "");

      lines.push(
        `  #grid(columns: (1fr, auto),`,
        `    [#text(weight: "bold", size: 10pt)[${degree}] #if "${school}" != "" [--- ${school}]],`,
        `    [#text(size: 8.5pt, fill: rgb("#6b7280"))[${year}]]`,
        `  )`,
        `  #v(4pt)`
      );
    }

    lines.push(`]`, `#v(4pt)`);
  }

  // Projects Section
  if (content.projects && content.projects.length > 0) {
    const projTitle = isGerman ? "Projekte" : isFrench ? "Projets Notables" : "Key Projects";
    lines.push(
      `#block(width: 100%)[`,
      `  #text(size: 11pt, weight: "bold", fill: rgb("#1f2937"))[${projTitle}]`,
      `  #line(length: 100%, stroke: 0.5pt + rgb("#e5e7eb"))`,
      `  #v(4pt)`
    );

    for (const item of content.projects) {
      const projName = escapeTypst(item.name || "");
      const tech = item.tech ? ` [${escapeTypst(item.tech)}]` : "";

      lines.push(
        `  #text(weight: "bold", size: 9.5pt)[${projName}]#text(size: 8.5pt, fill: rgb("#4b5563"))[${tech}]`
      );

      if (item.bullets && item.bullets.length > 0) {
        for (const b of item.bullets) {
          lines.push(`  - #text(size: 9pt)[${escapeTypst(b)}]`);
        }
      }
      lines.push(`  #v(4pt)`);
    }

    lines.push(`]`);
  }

  return lines.join("\n");
}
